"use client";

import { Provider } from "react-redux";
import "./styles/globals.css";
import type { Metadata } from "next";
import { store } from "../features/store";
import Navbar from "@/components/nav";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create next app",
  description: "Generated by create next application",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-50">
        <Provider store={store}>
          <Navbar />
          <main className="mt-28">{children}</main>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
